services:
  db:
    image: postgres:17                    
    container_name: postgres_db      

    environment:
      POSTGRES_DB: syslab_db    
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456

    ports:
      - "5434:5432"           

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: