# Generated by Django 6.0.5 on 2026-05-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='oauth_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='proveedor_oauth',
        ),
    ]
