# Generated by Django 6.0.5 on 2026-06-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0002_remove_usuario_oauth_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción de la intervención realizada al equipo.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_intervencion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='information_app.solicitud')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='information_app.tecnico')),
            ],
            options={
                'db_table': 'intervencion',
                'ordering': ['-fecha_intervencion'],
            },
        ),
    ]
