# Generated by Django 6.0.5 on 2026-06-22 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0004_request_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='datos_equipo_solicitado',
            field=models.JSONField(blank=True, help_text='Datos provisionales del equipo reportado por el solicitante.', null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='information_app.equipo'),
        ),
    ]
