# Generated by Django 6.0.5 on 2026-06-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0005_solicitud_datos_equipo_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='datos_equipo_solicitado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
