# Generated by Django 6.0.5 on 2026-06-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0006_solicitud_datos_equipo_solicitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividadUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('login', 'Inicio de sesión'), ('creacion_solicitud', 'Creación de solicitud'), ('cambio_estado', 'Cambio de estado de solicitud'), ('carga_adjunto', 'Carga de adjunto'), ('actualizacion_perfil', 'Actualización de perfil'), ('asignacion_rol', 'Asignación de rol'), ('cambio_estado_cuenta', 'Cambio de estado de cuenta')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actividades', to='information_app.usuario')),
            ],
            options={
                'db_table': 'historial_actividad_usuario',
                'ordering': ['-fecha'],
            },
        ),
    ]
