# Generated by Django 6.0.5 on 2026-07-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_app', '0007_protect_solicitud_y_configuracion_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='information_app.equipo'),
        ),
    ]
