# Generated by Django 6.0.5 on 2026-05-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción del contexto o propósito de los archivos adjuntos.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anexo',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('fuera_de_servicio', 'Fuera de Servicio'), ('dado_de_baja', 'Dado de Baja')], default='operativo', max_length=50)),
                ('criticidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=50)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'horario_atencion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('docente', 'Docente'), ('laboratorista', 'Laboratorista'), ('tecnico', 'Técnico')], default='docente', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('video', 'Video'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('tamanio_bytes', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='information_app.anexo')),
            ],
            options={
                'db_table': 'adjunto',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Diagnóstico inicial del problema reportado por el usuario.')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='information_app.equipo')),
                ('horario_agendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='information_app.horarioatencion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='information_app.usuario')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('mantenimiento_programado', 'Mantenimiento Programado'), ('asignacion_tecnico', 'Asignación de Técnico'), ('cambio_estado', 'Cambio de Estado'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='information_app.solicitud')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='anexo',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='information_app.solicitud'),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('especialidad', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_tecnico', serialize=False, to='information_app.usuario')),
            ],
            options={
                'db_table': 'tecnico',
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_app.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information_app.usuario')),
            ],
            options={
                'db_table': 'notificacion_usuario',
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatarios',
            field=models.ManyToManyField(related_name='notificaciones_recibidas', through='information_app.NotificacionUsuario', to='information_app.usuario'),
        ),
        migrations.CreateModel(
            name='HistorialEstadoSolicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('motivo', models.TextField(help_text='Razón del cambio de estado. Obligatorio en cambios manuales.')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='information_app.solicitud')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_realizados', to='information_app.usuario')),
            ],
            options={
                'db_table': 'historial_estado_solicitud',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='anexo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_creados', to='information_app.usuario'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='information_app.solicitud')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='information_app.tecnico')),
            ],
            options={
                'db_table': 'asignacion',
                'unique_together': {('solicitud', 'tecnico')},
            },
        ),
    ]
